#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [5]:
a = np.zeros(10)

#### 3. Как узнать объем памяти любого массива (★☆☆)

In [6]:
a.nbytes

80

#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [7]:
np.array(np.arange(10, 50, 1))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [8]:
np.array(np.arange(10, 50, 1))[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [16]:
a = np.array([1, 2, 0, 0, 4, 0])
a.nonzero()

(array([0, 1, 4]),)

#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [24]:
np.random.rand(3,3,3)

array([[[0.06679595, 0.64881532, 0.32753414],
        [0.5340267 , 0.13342766, 0.22169019],
        [0.74279166, 0.17449861, 0.81381333]],

       [[0.44967776, 0.19202068, 0.4740795 ],
        [0.08993763, 0.38397331, 0.37129372],
        [0.80981844, 0.23797912, 0.26888078]],

       [[0.48033573, 0.2540379 , 0.04192087],
        [0.51675621, 0.50280243, 0.55100885],
        [0.63124212, 0.9459285 , 0.62993293]]])

#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [26]:
a = np.random.rand(10,10)
a.min(), a.max()

(0.014094785573832591, 0.9810509283487785)

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [30]:
a = np.random.rand(30)
a.mean()

0.47539366436231584

#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [5]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [7]:
b = np.arange(6 * 7 * 8).reshape((6, 7, 8))
print(np.where(b == 99))
b[1][5][3]

(array([1]), array([5]), array([3]))


99

#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [52]:
np.random.rand(5,3) @ np.random.rand(3,2)

array([[0.28916846, 0.86337536],
       [0.27127343, 1.05807306],
       [0.67691082, 1.02660299],
       [0.58100111, 0.74985171],
       [0.32108404, 0.62815822]])

#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [60]:
a = np.random.randint(1, 11, 10)
print(a)
for i in np.arange(a.size):
    if a[i] == 8:
        a[i] = 3
    elif a[i] == 3:
        a[i] = 8
print(a)

[7 2 5 3 8 8 5 1 8 7]
[7 2 5 8 3 3 5 1 3 7]


In [73]:
a = np.random.randint(1, 11, 10)
print(a)
i8, i3 = np.where(a == 8), np.where(a == 3)
a[i8] = 3
a[i3] = 8
print(a) 

[2 2 9 5 2 7 3 3 3 5]
[2 2 9 5 2 7 8 8 8 5]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [78]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_2057/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_2057/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [9]:
a = np.array([0, 1, 2])
b = np.array([0, 3, 2])
print(a[a == b])
print(np.intersect1d(a, b))

[0 2]
[0 2]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [19]:
a = np.array([0, 1, 2]).astype(float)
b = np.array([0, 3, 2]).astype(float)

np.add(a, b, out=b)
print(a, b)
np.divide(a, 2, out=a)
print(a, b)
np.negative(a, out=a)
print(a, b)
np.multiply(a, b, out=a)
print(a, b)

[0. 1. 2.] [0. 4. 4.]
[0.  0.5 1. ] [0. 4. 4.]
[-0.  -0.5 -1. ] [0. 4. 4.]
[-0. -2. -4.] [0. 4. 4.]


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [18]:
np.tile(np.array(np.arange(5)), 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [22]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [28]:
np.sort(np.random.randint(0, 100, 10))

array([13, 14, 23, 26, 31, 38, 61, 67, 73, 74])

#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [12]:
a = np.arange(10)

In [13]:
%%time
np.add.accumulate(a)[-1]

CPU times: user 33 µs, sys: 15 µs, total: 48 µs
Wall time: 53.4 µs


45

In [14]:
%%time
np.sum(a)

CPU times: user 56 µs, sys: 26 µs, total: 82 µs
Wall time: 86.5 µs


45

#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [29]:
a = np.array([0, 1, 2])
b = np.array([0, 3, 2])

a == b

array([ True, False,  True])

#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [11]:
a = np.random.randn(10)
print(a)
a[a.argmax()] = 0
a

[ 0.81590308 -0.83868554 -0.42167042  0.9583928   1.37278935 -0.97695453
 -1.34453573  0.51942579 -1.65497734 -0.07259466]


array([ 0.81590308, -0.83868554, -0.42167042,  0.9583928 ,  0.        ,
       -0.97695453, -1.34453573,  0.51942579, -1.65497734, -0.07259466])

#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [20]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(dtype)
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max, end="\n\n")
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(dtype)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps, end="\n\n")
    

<class 'numpy.int8'>
-128
127

<class 'numpy.int16'>
-32768
32767

<class 'numpy.int32'>
-2147483648
2147483647

<class 'numpy.int64'>
-9223372036854775808
9223372036854775807

<class 'numpy.float16'>
-65500.0
65500.0
0.000977

<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07

<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16

<class 'numpy.float128'>
-1.189731495357231765e+4932
1.189731495357231765e+4932
1.084202172485504434e-19



#### 26. Как вывести все значения большого массива? (★★☆)

In [67]:
from pickletools import float8

a = np.random.randn(50, 50)
np.set_printoptions(
    precision=3,
    edgeitems=3,
    sign="-",
    linewidth=100
)
print(a)

[[-1.478 -2.095 -1.107 ...  0.469  0.738 -1.643]
 [ 1.317 -1.123  0.614 ...  0.179  0.853 -0.924]
 [-0.769  1.42  -0.826 ... -0.79  -0.85  -0.069]
 ...
 [-0.282 -1.601 -0.901 ... -0.695  0.195  0.478]
 [-0.133 -1.416 -1.449 ... -0.734 -2.173 -0.147]
 [ 0.428  0.498  1.897 ... -0.366 -0.967  1.131]]


#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [42]:
a = np.random.randn(100, 2)

x = a[:,0].reshape(1, -1)
y = a[:,1].reshape(1, -1)

np.sqrt( (x - x.T)**2 + (y - y.T)**2)

array([[0.        , 1.18869565, 2.21718463, ..., 1.90188883, 2.57784126,
        1.90534413],
       [1.18869565, 0.        , 1.24411196, ..., 0.90920387, 1.59058083,
        3.08227792],
       [2.21718463, 1.24411196, 0.        , ..., 0.33654597, 0.36173385,
        3.93094428],
       ...,
       [1.90188883, 0.90920387, 0.33654597, ..., 0.        , 0.69299187,
        3.6607355 ],
       [2.57784126, 1.59058083, 0.36173385, ..., 0.69299187, 0.        ,
        4.2706527 ],
       [1.90534413, 3.08227792, 3.93094428, ..., 3.6607355 , 4.2706527 ,
        0.        ]])

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [89]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32)
a


[0. 1. 2. ... 7. 8. 9.]


array([0, 1, 2, ..., 7, 8, 9], dtype=int32)

#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [91]:
a = np.genfromtxt("29.txt", delimiter=",")
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [16]:
a = np.arange(10).reshape(5, -1)
# print(a)
# print(a.mean(axis=1, keepdims=True).shape)
a - a.mean(axis=1, keepdims=True)

array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]])

#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [32]:
a = np.zeros(10)
index = np.random.randint(0, len(a), 20)
a += np.bincount(index)
print(a, np.sum(a))

[3. 1. 1. 4. 2. 2. 1. 3. 0. 3.] 20.0


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [73]:
x = np.random.randint(0, 5, 5)
f = np.random.randint(0, 5, 5)

print(f"{f=}")
print(f"{x=}")

i = np.unique(np.random.randint(0, 5, 2))

print(f"{i=}")

f[i] = x[i]

print(f"{f=}")

f=array([4, 2, 2, 2, 4])
x=array([3, 1, 0, 2, 3])
i=array([0, 3])
f=array([3, 2, 2, 2, 4])


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [24]:
a = np.random.randint(0, 5, (2, 3, 2, 3))
print(a)
a.sum(axis=(-2,-1))

[[[[3 2 4]
   [4 3 4]]

  [[1 2 3]
   [0 1 3]]

  [[0 3 1]
   [4 3 2]]]


 [[[0 4 2]
   [2 0 4]]

  [[2 3 0]
   [2 4 3]]

  [[4 1 4]
   [1 1 2]]]]


array([[20, 10, 13],
       [12, 14, 13]])

#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [65]:
a = np.arange(1, 6)
zeros = np.zeros((a.shape[0], 3))
stacked = np.hstack((a.reshape(5, 1), zeros))
print(stacked)
print(stacked.reshape(-1)[:-3].astype(int))


[[1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [3. 0. 0. 0.]
 [4. 0. 0. 0.]
 [5. 0. 0. 0.]]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [66]:
casted = np.broadcast_to(np.random.rand(5, 5), (3, 5, 5))
np.random.rand(5, 5, 3) @ casted.reshape(5, 3, 5)

array([[[1.06163684, 0.22192247, 0.27903149, 0.72176681, 1.05109071],
        [1.43198045, 0.15617882, 0.30887979, 0.83488344, 1.24173921],
        [1.42146252, 0.23280287, 0.38860408, 0.82418366, 1.23806638],
        [1.72035017, 0.67557206, 0.72515889, 1.25699188, 1.84496461],
        [1.32872354, 0.36961139, 0.4314607 , 0.92371232, 1.35102951]],

       [[0.67938366, 0.71691714, 0.48230377, 0.82639402, 1.12932209],
        [0.40716595, 0.43359855, 0.31313214, 0.4814959 , 0.6462946 ],
        [0.67755171, 0.68809358, 0.30868445, 0.92515943, 1.34298429],
        [0.54157314, 0.47483271, 0.30286801, 0.55001087, 1.11663351],
        [0.48987644, 0.58672357, 0.29670346, 0.77086837, 0.77313188]],

       [[0.41490224, 0.04721658, 0.08304824, 0.23791378, 0.39526804],
        [1.34417187, 0.15477417, 0.2618297 , 0.8046116 , 1.28144883],
        [1.29122576, 0.17707808, 0.24739957, 0.76509632, 1.36521162],
        [0.84907346, 0.22604849, 0.11313326, 0.63889803, 1.37883338],
        [0.90542

#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [51]:
np.convolve(np.arange(5), np.ones(3) / 3, "valid")

array([1., 2., 3.])

#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [50]:
z = np.arange(1, 15)
r = [np.arange(i, i + 3) for i in z]
r[:-2]

[array([1, 2, 3]),
 array([2, 3, 4]),
 array([3, 4, 5]),
 array([4, 5, 6]),
 array([5, 6, 7]),
 array([6, 7, 8]),
 array([7, 8, 9]),
 array([ 8,  9, 10]),
 array([ 9, 10, 11]),
 array([10, 11, 12]),
 array([11, 12, 13]),
 array([12, 13, 14])]

#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [61]:
p0 = np.random.randint(10, size=(10, 2))
p1 = np.random.randint(10, size=(10, 2))
p = np.random.randint(10, size=(10, 2))

x0 = p0[:, 0]
y0 = p0[:, 1]

x1 = p1[:, 0]
y1 = p1[:, 1]

x = p[:, 0]
y = p[:, 1]

np.abs((y1 - y0) * x - (x1 - x0) * y + x1 * y0 - y1 * x0) / np.sqrt((y1 - y0)**2 + (x1 - x0)**2)

array([3.12347524, 0.16439899, 4.24264069, 1.        , 0.        ,
       0.89442719, 2.44120041, 2.6303838 , 2.        , 0.2773501 ])

#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [157]:
z = np.arange(1, 15)
r = [np.arange(i, i + 4) for i in z]
r[:-3]

[array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([3, 4, 5, 6]),
 array([4, 5, 6, 7]),
 array([5, 6, 7, 8]),
 array([6, 7, 8, 9]),
 array([ 7,  8,  9, 10]),
 array([ 8,  9, 10, 11]),
 array([ 9, 10, 11, 12]),
 array([10, 11, 12, 13]),
 array([11, 12, 13, 14])]

#### 40. Найдите ранг случайной матрицы (★★★)

In [150]:
a = np.random.uniform(0, 1, (10,10))
np.linalg.matrix_rank(a)

10

#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [26]:
a = np.random.randint(0, 3, 5)
unique_values, unique_counts = np.unique(a, return_counts=True)
print(a)
print(f"{unique_values = }")
print(f"{unique_counts = }")

print(unique_values[unique_counts == unique_counts.max()])

[1 0 2 0 1]
unique_values = array([0, 1, 2])
unique_counts = array([2, 2, 1])
[0 1]


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [94]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
print(c)
print(np.where(c.any((3,1))))
print(np.where(c.any((3,1)).all(1)))
print(np.where(c.any((3,1)).all(1))[0])


[[[[False False]
   [False False]]

  [[False  True]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [ True False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[ True False]
   [False  True]]

  [[False  True]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[ True False]
   [False  True]]

  [[ True False]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [ True False]]]


 [[[False False]
   [False False]]

  [[False  True]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False  True]
   [False False]]

  [[ True False]
   [False  True]]

  [[False False]
   [False False]]]]
(array([0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 7]), array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1]))
(array([1, 2, 3, 7]),)
[1 2 3 

#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [47]:
a = np.random.randint(0, 5, (20, 20))
b = np.random.randint(3, 7, (20, 20))

print(np.union1d(a, b))

[0 1 2 3 4 5 6]
